/**
 * Hype phrases — the curated things people can say about someone's day.
 *
 * ONE POOL PER LANGUAGE, NOT TRANSLATIONS. This is a deliberate departure
 * from the EN/DE parity rule in start.md §11, and the reason is that humour
 * does not survive translation: "Built different" has no German equivalent
 * that is also funny, and forcing a 1:1 mapping produced German that read as
 * translated English. Each language therefore has its own independent list,
 * of its own length, written in that language.
 *
 * The German locale draws from BOTH `de` (High German) and `gsw` (Swiss
 * German) — the community is Swiss-led and the dialect lines are the funniest
 * ones in the set.
 *
 * A phrase is rendered IN THE LANGUAGE IT WAS SENT IN, never translated,
 * because it is a quote: it is what a specific person chose to say. That
 * matches how feed captions already work (start.md §5 — user-authored text is
 * shown as written). It is the same reason ids are stored rather than text:
 * the wording can be improved later without rewriting history.
 *
 * THE BAR FOR A PHRASE: it must read as unambiguous support at a glance, to
 * someone who is tired and having a hard day. Rejected on sight —
 *   - anything needing a parenthetical to clarify it is a compliment
 *     ("Genuinely unwell (complimentary)") — the disclaimer IS the tell;
 *   - backhanded praise ("You are making the rest of us look bad");
 *   - mental-health words used as intensifiers (insane, mental, unhinged);
 *   - anything implying the person is overdoing it or not resting;
 *   - vulgar intensifiers, however common in speech ("huere");
 *   - "beast" and similar, retired by start.md §14;
 *   - claims that are not true of this product (there is no leaderboard).
 * Numbering gaps below are deliberate: 43 phrases were removed against this
 * bar and their ids were NOT reused.
 *
 * IDS ARE PERMANENT. They are stored in daily_logs.hype_phrase_id. Never
 * renumber or reuse one; only ever append. Editing a phrase's `text` is fine.
 */

import type { Locale } from './i18n';
import { interpolate } from './i18n';

/** Swiss German is its own pool, not a variant of `de`. */
export type HypeLang = 'en' | 'de' | 'gsw';

export interface HypePhrase {
  id: string;
  lang: HypeLang;
  text: string;
}

/**
 * Which pools a given app locale draws from when picking a phrase.
 * A German-speaking user gets High German and Swiss German; an English one
 * gets English only.
 */
export const POOLS_FOR_LOCALE: Record<Locale, HypeLang[]> = {
  en: ['en'],
  de: ['de', 'gsw'],
};

export const HYPE_PHRASES: HypePhrase[] = [
  { id: 'en-001', lang: 'en', text: 'Absolute unit' },
  { id: 'en-002', lang: 'en', text: 'Certified machine' },
  { id: 'en-003', lang: 'en', text: 'You are a god' },
  { id: 'en-004', lang: 'en', text: 'Built different, confirmed' },
  { id: 'en-005', lang: 'en', text: 'Day {days}?! Screenshot this' },
  { id: 'en-006', lang: 'en', text: 'Scientists are studying you' },
  { id: 'en-007', lang: 'en', text: 'This should be illegal' },
  { id: 'en-009', lang: 'en', text: 'No notes. Flawless' },
  { id: 'en-012', lang: 'en', text: 'Your excuses filed for bankruptcy' },
  { id: 'en-014', lang: 'en', text: 'Woke up and chose consistency' },
  { id: 'en-016', lang: 'en', text: 'Sir. Ma\'am. Legend' },
  { id: 'en-017', lang: 'en', text: 'This is not normal behaviour and I respect it' },
  { id: 'en-018', lang: 'en', text: 'Put this in a museum' },
  { id: 'en-019', lang: 'en', text: 'Unreasonably impressive' },
  { id: 'en-023', lang: 'en', text: 'Absolute weapon' },
  { id: 'en-024', lang: 'en', text: 'Day {days} and still going. Ridiculous' },
  { id: 'en-025', lang: 'en', text: 'Somebody hire this person as a motivational poster' },
  { id: 'en-026', lang: 'en', text: 'Your future self just high-fived you' },
  { id: 'en-027', lang: 'en', text: 'That is a whole personality now' },
  { id: 'en-029', lang: 'en', text: 'Cannot be stopped, only observed' },
  { id: 'en-030', lang: 'en', text: 'The streak is getting suspicious' },
  { id: 'en-031', lang: 'en', text: 'Sheer force of will, apparently' },
  { id: 'en-032', lang: 'en', text: 'This is a documentary in the making' },
  { id: 'en-033', lang: 'en', text: 'Peak human behaviour' },
  { id: 'en-034', lang: 'en', text: 'Your alarm clock fears you' },
  { id: 'en-036', lang: 'en', text: 'Chef\'s kiss' },
  { id: 'en-037', lang: 'en', text: 'Immaculate' },
  { id: 'en-038', lang: 'en', text: 'Simply cracked' },
  { id: 'en-039', lang: 'en', text: 'Elite behaviour detected' },
  { id: 'en-040', lang: 'en', text: 'Frankly heroic' },
  { id: 'en-044', lang: 'en', text: 'Big main character energy' },
  { id: 'en-045', lang: 'en', text: 'This is the content I signed up for' },
  { id: 'en-046', lang: 'en', text: 'Actual proof that willpower exists' },
  { id: 'en-048', lang: 'en', text: 'Legally a machine at this point' },
  { id: 'en-049', lang: 'en', text: 'Consistency has entered the chat' },
  { id: 'en-051', lang: 'en', text: 'The grind respects you back' },
  { id: 'en-052', lang: 'en', text: 'That\'s a lot of days. Impressive' },
  { id: 'en-053', lang: 'en', text: 'Wildly underrated performance' },
  { id: 'en-054', lang: 'en', text: 'Somebody give this person a medal' },
  { id: 'en-055', lang: 'en', text: 'Ridiculously solid' },
  { id: 'en-056', lang: 'en', text: 'Unshakeable' },
  { id: 'en-057', lang: 'en', text: 'The kind of person calendars were invented for' },
  { id: 'en-058', lang: 'en', text: 'Ten out of ten, no crumbs' },
  { id: 'en-059', lang: 'en', text: 'This is why you are the favourite' },
  { id: 'en-060', lang: 'en', text: 'Doing numbers' },
  { id: 'en-061', lang: 'en', text: 'Certified locked in' },
  { id: 'en-062', lang: 'en', text: 'No days off, apparently' },
  { id: 'en-063', lang: 'en', text: 'The consistency is genuinely intimidating' },
  { id: 'en-064', lang: 'en', text: 'Objectively excellent' },
  { id: 'en-065', lang: 'en', text: 'That is craftsmanship' },
  { id: 'en-066', lang: 'en', text: 'Delicious work' },
  { id: 'en-069', lang: 'en', text: 'Look at this absolute professional' },
  { id: 'en-070', lang: 'en', text: 'Somebody is not messing around' },
  { id: 'en-071', lang: 'en', text: 'Straight up inspiring' },
  { id: 'en-072', lang: 'en', text: 'Making it look easy, which it is not' },
  { id: 'en-073', lang: 'en', text: 'Quietly dominating' },
  { id: 'en-074', lang: 'en', text: 'This is what showing up looks like' },
  { id: 'en-075', lang: 'en', text: 'Textbook execution' },
  { id: 'en-076', lang: 'en', text: 'Unfairly consistent' },
  { id: 'en-077', lang: 'en', text: 'Just built like that' },
  { id: 'en-078', lang: 'en', text: 'Zero excuses detected' },
  { id: 'en-079', lang: 'en', text: 'The bar is on the ceiling now' },
  { id: 'en-080', lang: 'en', text: 'Frighteningly reliable' },
  { id: 'en-081', lang: 'en', text: 'Certified day-winner' },
  { id: 'en-082', lang: 'en', text: 'Absolute scenes' },
  { id: 'en-083', lang: 'en', text: 'You did the thing. Again' },
  { id: 'en-084', lang: 'en', text: 'The compound interest of showing up' },
  { id: 'en-085', lang: 'en', text: 'Respect, genuinely' },
  { id: 'en-086', lang: 'en', text: 'This is a masterclass' },
  { id: 'en-087', lang: 'en', text: 'Casually excellent' },
  { id: 'en-088', lang: 'en', text: 'That\'s the good stuff' },
  { id: 'en-089', lang: 'en', text: 'Somebody bottle this energy' },
  { id: 'en-090', lang: 'en', text: 'Full marks' },
  { id: 'en-091', lang: 'en', text: 'Not a single wasted day' },
  { id: 'en-092', lang: 'en', text: 'The follow-through is unreal' },
  { id: 'en-093', lang: 'en', text: 'Winning quietly' },
  { id: 'en-094', lang: 'en', text: 'Never in doubt' },
  { id: 'en-095', lang: 'en', text: 'That was never even close' },
  { id: 'en-096', lang: 'en', text: 'Ice cold execution' },
  { id: 'en-097', lang: 'en', text: 'Sensational' },
  { id: 'en-098', lang: 'en', text: 'Cracked open the day and won' },
  { id: 'en-099', lang: 'en', text: 'Deeply impressive' },
  { id: 'en-104', lang: 'en', text: 'The receipts are stacking up' },
  { id: 'en-105', lang: 'en', text: 'You are doing the thing most people talk about' },
  { id: 'en-106', lang: 'en', text: 'Applause. Genuine applause' },
  { id: 'en-107', lang: 'en', text: 'The work is working' },
  { id: 'en-108', lang: 'en', text: 'Consistently ridiculous' },
  { id: 'en-109', lang: 'en', text: 'No thoughts, just execution' },
  { id: 'en-110', lang: 'en', text: 'Built to last' },
  { id: 'en-111', lang: 'en', text: 'Day {days}. Absolute cinema' },
  { id: 'en-112', lang: 'en', text: 'That is a serious streak' },
  { id: 'en-113', lang: 'en', text: 'Effortlessly relentless' },
  { id: 'en-114', lang: 'en', text: 'This is the blueprint' },
  { id: 'en-115', lang: 'en', text: 'Beautiful work' },
  { id: 'en-116', lang: 'en', text: 'Certified grinder' },
  { id: 'en-117', lang: 'en', text: 'Doing what you said you would do. Rare' },
  { id: 'en-118', lang: 'en', text: 'Extremely locked in' },
  { id: 'en-119', lang: 'en', text: 'This is elite' },
  { id: 'en-121', lang: 'en', text: 'Actually inspiring, no irony' },
  { id: 'en-122', lang: 'en', text: 'Look at that follow-through' },
  { id: 'en-123', lang: 'en', text: 'Somebody get this person a documentary crew' },
  { id: 'en-124', lang: 'en', text: 'Immovable' },
  { id: 'en-125', lang: 'en', text: 'Genuinely one of the greats' },
  { id: 'en-126', lang: 'en', text: 'No skips' },
  { id: 'en-127', lang: 'en', text: 'Absolutely dialled in' },
  { id: 'en-128', lang: 'en', text: 'That is discipline you can hear' },
  { id: 'en-129', lang: 'en', text: 'Frankly outrageous' },
  { id: 'en-130', lang: 'en', text: 'Set the standard again' },
  { id: 'en-131', lang: 'en', text: 'Your momentum is showing' },
  { id: 'en-132', lang: 'en', text: 'Nothing but respect' },
  { id: 'en-133', lang: 'en', text: 'Ridiculous in the best way' },
  { id: 'en-134', lang: 'en', text: 'This is peak' },
  { id: 'en-135', lang: 'en', text: 'Steady as anything' },
  { id: 'en-136', lang: 'en', text: 'Certified hard worker' },
  { id: 'en-137', lang: 'en', text: 'The consistency tax has been paid' },
  { id: 'en-138', lang: 'en', text: 'You made that look routine' },
  { id: 'en-139', lang: 'en', text: 'The routine is the flex' },
  { id: 'en-140', lang: 'en', text: 'Never missed, never will' },
  { id: 'en-141', lang: 'en', text: 'Unbothered, moisturised, on streak' },
  { id: 'en-142', lang: 'en', text: 'The mindset is unreal' },
  { id: 'en-143', lang: 'en', text: 'Doing the boring thing brilliantly' },
  { id: 'en-144', lang: 'en', text: 'That is a serious human' },
  { id: 'en-145', lang: 'en', text: 'This should not be possible' },
  { id: 'en-146', lang: 'en', text: 'Cold blooded' },
  { id: 'en-147', lang: 'en', text: 'Locked. In.' },
  { id: 'en-148', lang: 'en', text: 'This is going in the highlight reel' },
  { id: 'en-149', lang: 'en', text: 'Somebody is building something' },
  { id: 'en-150', lang: 'en', text: 'Quiet excellence' },
  { id: 'en-151', lang: 'en', text: 'Textbook. Frame it' },
  { id: 'en-152', lang: 'en', text: 'That is a professional' },
  { id: 'en-153', lang: 'en', text: 'Big respect' },
  { id: 'en-154', lang: 'en', text: 'Untouchable' },
  { id: 'en-155', lang: 'en', text: 'Absolute rock' },
  { id: 'en-156', lang: 'en', text: 'Your discipline needs its own postcode' },
  { id: 'en-157', lang: 'en', text: 'This is what the app was made for' },
  { id: 'en-158', lang: 'en', text: 'Unreal follow-through' },
  { id: 'en-159', lang: 'en', text: 'Consistency is a superpower and you have it' },
  { id: 'en-160', lang: 'en', text: 'Doing it properly' },
  { id: 'en-161', lang: 'en', text: 'Look at this dedication' },
  { id: 'en-162', lang: 'en', text: 'Somebody has a plan and is executing it' },
  { id: 'en-163', lang: 'en', text: 'That is a serious operator' },
  { id: 'en-164', lang: 'en', text: 'Straight up excellent' },
  { id: 'en-165', lang: 'en', text: 'The routine is undefeated' },
  { id: 'en-166', lang: 'en', text: 'That was clinical' },
  { id: 'en-167', lang: 'en', text: 'No wasted motion' },
  { id: 'en-168', lang: 'en', text: 'This is masterful' },
  { id: 'en-169', lang: 'en', text: 'Absolutely no notes' },
  { id: 'en-170', lang: 'en', text: 'You are the standard' },
  { id: 'en-171', lang: 'en', text: 'Untouchable form' },
  { id: 'en-172', lang: 'en', text: 'Genuinely brilliant' },
  { id: 'en-173', lang: 'en', text: 'That is how it is done' },
  { id: 'en-174', lang: 'en', text: 'Extremely well played' },
  { id: 'en-175', lang: 'en', text: 'Look at you go' },
  { id: 'en-176', lang: 'en', text: 'The streak is a lifestyle now' },
  { id: 'en-177', lang: 'en', text: 'Effort recognised' },
  { id: 'en-178', lang: 'en', text: 'Certified relentless' },
  { id: 'en-179', lang: 'en', text: 'No half measures' },
  { id: 'en-180', lang: 'en', text: 'Serious about it' },
  { id: 'en-181', lang: 'en', text: 'Immaculate vibes' },
  { id: 'en-182', lang: 'en', text: 'Nothing casual about this' },
  { id: 'en-183', lang: 'en', text: 'Straight machine behaviour' },
  { id: 'en-184', lang: 'en', text: 'The consistency is loud' },
  { id: 'en-185', lang: 'en', text: 'Doing the work quietly' },
  { id: 'en-186', lang: 'en', text: 'Total control' },
  { id: 'en-187', lang: 'en', text: 'Simply excellent' },
  { id: 'en-188', lang: 'en', text: 'This is a habit now, not a hope' },
  { id: 'en-189', lang: 'en', text: 'Ruthlessly consistent' },
  { id: 'en-190', lang: 'en', text: 'Certified good egg with great discipline' },
  { id: 'en-191', lang: 'en', text: 'The bar has been raised again' },
  { id: 'en-192', lang: 'en', text: 'This is what commitment looks like' },
  { id: 'en-193', lang: 'en', text: 'Somebody woke up and delivered' },
  { id: 'en-194', lang: 'en', text: 'That is a serious result' },
  { id: 'en-195', lang: 'en', text: 'No gaps' },
  { id: 'en-196', lang: 'en', text: 'The follow-through is elite' },
  { id: 'en-197', lang: 'en', text: 'Impressive does not cover it' },
  { id: 'en-198', lang: 'en', text: 'Extremely solid' },
  { id: 'en-199', lang: 'en', text: 'Real ones do this' },
  { id: 'en-200', lang: 'en', text: 'Consistently outstanding' },
  { id: 'en-201', lang: 'en', text: 'That is a proper effort' },
  { id: 'en-202', lang: 'en', text: 'Look at the shape of that streak' },
  { id: 'en-203', lang: 'en', text: 'Doing it for real' },
  { id: 'en-204', lang: 'en', text: 'This is the good stuff' },
  { id: 'en-205', lang: 'en', text: 'Perfectly executed' },
  { id: 'en-206', lang: 'en', text: 'Absolutely locked' },
  { id: 'en-207', lang: 'en', text: 'Nothing to fix' },
  { id: 'en-208', lang: 'en', text: 'Sheer quality' },
  { id: 'en-209', lang: 'en', text: 'Textbook consistency' },
  { id: 'en-210', lang: 'en', text: 'That is a serious habit' },
  { id: 'en-211', lang: 'en', text: 'Genuinely excellent work' },
  { id: 'en-212', lang: 'en', text: 'Unmatched' },
  { id: 'en-213', lang: 'en', text: 'Somebody is on a mission' },
  { id: 'en-214', lang: 'en', text: 'That is dedication' },
  { id: 'en-215', lang: 'en', text: 'Complete control' },
  { id: 'en-216', lang: 'en', text: 'Excellent as always' },
  { id: 'en-217', lang: 'en', text: 'No notes whatsoever' },
  { id: 'en-218', lang: 'en', text: 'This is elite behaviour' },
  { id: 'en-219', lang: 'en', text: 'Total commitment' },
  { id: 'en-220', lang: 'en', text: 'Look at that discipline' },
  { id: 'en-221', lang: 'en', text: 'Consistently brilliant' },
  { id: 'en-222', lang: 'en', text: 'A serious performance' },
  { id: 'en-223', lang: 'en', text: 'That is exceptional' },
  { id: 'en-224', lang: 'en', text: 'Unbelievably consistent' },
  { id: 'en-225', lang: 'en', text: 'Somebody is different' },
  { id: 'en-226', lang: 'en', text: 'Absolutely superb' },
  { id: 'en-227', lang: 'en', text: 'That is quality' },
  { id: 'en-228', lang: 'en', text: 'Very impressive indeed' },
  { id: 'en-229', lang: 'en', text: 'Real consistency' },
  { id: 'en-230', lang: 'en', text: 'Nothing but excellence' },
  { id: 'en-231', lang: 'en', text: 'That is proper work' },
  { id: 'en-232', lang: 'en', text: 'Fully committed' },
  { id: 'en-233', lang: 'en', text: 'Outstanding' },
  { id: 'en-234', lang: 'en', text: 'Seriously good' },
  { id: 'en-235', lang: 'en', text: 'Look at this' },
  { id: 'en-236', lang: 'en', text: 'Remarkable' },
  { id: 'en-237', lang: 'en', text: 'Simply brilliant' },
  { id: 'en-238', lang: 'en', text: 'Very well done' },
  { id: 'en-239', lang: 'en', text: 'Extremely impressive' },
  { id: 'en-240', lang: 'en', text: 'Genuinely great' },
  { id: 'en-241', lang: 'en', text: 'Consistently excellent' },
  { id: 'en-242', lang: 'en', text: 'Absolutely brilliant' },
  { id: 'en-243', lang: 'en', text: 'Top tier' },
  { id: 'en-244', lang: 'en', text: 'First class' },
  { id: 'en-245', lang: 'en', text: 'Exceptional work' },
  { id: 'en-246', lang: 'en', text: 'Superb' },
  { id: 'en-247', lang: 'en', text: 'Magnificent' },
  { id: 'en-248', lang: 'en', text: 'Tremendous' },
  { id: 'en-249', lang: 'en', text: 'Class act' },
  { id: 'en-250', lang: 'en', text: 'Serious quality' },
  { id: 'en-251', lang: 'en', text: 'Beautifully done' },
  { id: 'en-252', lang: 'en', text: 'Perfect' },
  { id: 'en-253', lang: 'en', text: 'Outstanding effort' },
  { id: 'en-254', lang: 'en', text: 'Really impressive' },
  { id: 'en-255', lang: 'en', text: 'Genuinely good' },
  { id: 'en-256', lang: 'en', text: 'Very strong' },
  { id: 'en-257', lang: 'en', text: 'Excellent' },
  { id: 'en-258', lang: 'en', text: 'Brilliant work' },
  { id: 'en-259', lang: 'en', text: 'Well played' },
  { id: 'en-260', lang: 'en', text: 'Nicely done' },
  { id: 'en-261', lang: 'en', text: 'Strong showing' },
  { id: 'en-262', lang: 'en', text: 'Solid as ever' },
  { id: 'en-263', lang: 'en', text: 'Great stuff' },
  { id: 'en-264', lang: 'en', text: 'Proper job' },
  { id: 'en-265', lang: 'en', text: 'Nailed it' },
  { id: 'en-266', lang: 'en', text: 'Crushed it' },
  { id: 'en-267', lang: 'en', text: 'Smashed it' },
  { id: 'en-268', lang: 'en', text: 'Owned it' },
  { id: 'en-269', lang: 'en', text: 'Delivered' },
  { id: 'en-270', lang: 'en', text: 'Executed' },
  { id: 'en-271', lang: 'en', text: 'Handled' },
  { id: 'en-272', lang: 'en', text: 'Sorted' },
  { id: 'en-273', lang: 'en', text: 'Done and dusted' },
  { id: 'en-274', lang: 'en', text: 'In the bag' },
  { id: 'en-275', lang: 'en', text: 'Money' },
  { id: 'en-276', lang: 'en', text: 'Clean' },
  { id: 'en-277', lang: 'en', text: 'Sharp' },
  { id: 'en-278', lang: 'en', text: 'Slick' },
  { id: 'en-279', lang: 'en', text: 'Crisp' },
  { id: 'en-280', lang: 'en', text: 'Tidy' },
  { id: 'en-281', lang: 'en', text: 'Class' },
  { id: 'en-282', lang: 'en', text: 'Quality' },
  { id: 'en-283', lang: 'en', text: 'Elite' },
  { id: 'en-284', lang: 'en', text: 'Massive' },
  { id: 'en-285', lang: 'en', text: 'Huge' },
  { id: 'en-286', lang: 'en', text: 'Unreal' },
  { id: 'en-289', lang: 'en', text: 'Ridiculous' },
  { id: 'en-290', lang: 'en', text: 'Outrageous' },
  { id: 'en-291', lang: 'en', text: 'Absurd' },
  { id: 'en-292', lang: 'en', text: 'Unbelievable' },
  { id: 'en-293', lang: 'en', text: 'Incredible' },
  { id: 'en-294', lang: 'en', text: 'Amazing' },
  { id: 'en-295', lang: 'en', text: 'Fantastic' },
  { id: 'en-296', lang: 'en', text: 'Superb effort' },
  { id: 'en-297', lang: 'en', text: 'Top work' },
  { id: 'en-298', lang: 'en', text: 'Great going' },
  { id: 'en-299', lang: 'en', text: 'Keep it rolling' },
  { id: 'en-300', lang: 'en', text: 'Onwards' },
  { id: 'en-301', lang: 'en', text: 'Momentum' },
  { id: 'en-302', lang: 'en', text: 'Relentless' },
  { id: 'en-303', lang: 'en', text: 'Unstoppable' },
  { id: 'en-304', lang: 'en', text: 'Determined' },
  { id: 'en-305', lang: 'en', text: 'Focused' },
  { id: 'en-306', lang: 'en', text: 'Committed' },
  { id: 'en-307', lang: 'en', text: 'Disciplined' },
  { id: 'en-308', lang: 'en', text: 'Consistent' },
  { id: 'en-309', lang: 'en', text: 'Reliable' },
  { id: 'en-310', lang: 'en', text: 'Steady' },
  { id: 'en-311', lang: 'en', text: 'Solid' },
  { id: 'en-312', lang: 'en', text: 'Strong' },
  { id: 'en-313', lang: 'en', text: 'Dedicated' },
  { id: 'en-314', lang: 'en', text: 'Driven' },
  { id: 'en-315', lang: 'en', text: 'Motivated' },
  { id: 'en-316', lang: 'en', text: 'Locked in' },
  { id: 'en-317', lang: 'en', text: 'Dialled in' },
  { id: 'en-318', lang: 'en', text: 'Zoned in' },
  { id: 'en-319', lang: 'en', text: 'On it' },
  { id: 'en-320', lang: 'en', text: 'Firing' },
  { id: 'en-321', lang: 'en', text: 'Cooking' },
  { id: 'en-322', lang: 'en', text: 'Flying' },
  { id: 'en-323', lang: 'en', text: 'Cruising' },
  { id: 'en-324', lang: 'en', text: 'Rolling' },
  { id: 'en-325', lang: 'en', text: 'Building' },
  { id: 'en-326', lang: 'en', text: 'Grinding' },
  { id: 'en-327', lang: 'en', text: 'Climbing' },
  { id: 'en-328', lang: 'en', text: 'Progressing' },
  { id: 'en-329', lang: 'en', text: 'Improving' },
  { id: 'en-330', lang: 'en', text: 'Winning' },
  { id: 'en-331', lang: 'en', text: 'Thriving' },
  { id: 'en-332', lang: 'en', text: 'Excelling' },
  { id: 'en-333', lang: 'en', text: 'Delivering' },
  { id: 'en-334', lang: 'en', text: 'Performing' },
  { id: 'en-335', lang: 'en', text: 'Showing up' },
  { id: 'en-336', lang: 'en', text: 'Following through' },
  { id: 'en-337', lang: 'en', text: 'Getting it done' },
  { id: 'en-338', lang: 'en', text: 'Making it count' },
  { id: 'en-339', lang: 'en', text: 'Putting in the work' },
  { id: 'en-340', lang: 'en', text: 'Doing the reps' },
  { id: 'en-341', lang: 'en', text: 'Stacking days' },
  { id: 'en-342', lang: 'en', text: 'Banking wins' },
  { id: 'en-343', lang: 'en', text: 'Compounding' },
  { id: 'en-344', lang: 'en', text: 'Levelling up' },
  { id: 'de-001', lang: 'de', text: 'Maschine' },
  { id: 'de-003', lang: 'de', text: 'Tag {days}?! Screenshot machen' },
  { id: 'de-004', lang: 'de', text: 'Alter, was geht ab' },
  { id: 'de-005', lang: 'de', text: 'Respekt, ehrlich' },
  { id: 'de-006', lang: 'de', text: 'Das sollte verboten sein' },
  { id: 'de-007', lang: 'de', text: 'Wissenschaftler untersuchen dich gerade' },
  { id: 'de-008', lang: 'de', text: 'Deine Ausreden haben Insolvenz angemeldet' },
  { id: 'de-009', lang: 'de', text: 'Einfach mal abliefern' },
  { id: 'de-010', lang: 'de', text: 'Komplett drin' },
  { id: 'de-011', lang: 'de', text: 'Das ist schon fast unhöflich diszipliniert' },
  { id: 'de-013', lang: 'de', text: 'Absolut irre' },
  { id: 'de-014', lang: 'de', text: 'Kann man nicht stoppen, nur beobachten' },
  { id: 'de-015', lang: 'de', text: 'Dein Wecker hat Angst vor dir' },
  { id: 'de-017', lang: 'de', text: 'Sauber' },
  { id: 'de-018', lang: 'de', text: 'Makellos' },
  { id: 'de-019', lang: 'de', text: 'Einfach gebaut dafür' },
  { id: 'de-020', lang: 'de', text: 'Elite-Verhalten festgestellt' },
  { id: 'de-021', lang: 'de', text: 'Ehrlich gesagt heldenhaft' },
  { id: 'de-024', lang: 'de', text: 'Riesen-Energie' },
  { id: 'de-025', lang: 'de', text: 'Genau dafür bin ich hier' },
  { id: 'de-026', lang: 'de', text: 'Der lebende Beweis, dass Willenskraft existiert' },
  { id: 'de-027', lang: 'de', text: 'Rein rechtlich bist du jetzt eine Maschine' },
  { id: 'de-028', lang: 'de', text: 'Konsequenz hat den Chat betreten' },
  { id: 'de-029', lang: 'de', text: 'Der Grind respektiert dich zurück' },
  { id: 'de-030', lang: 'de', text: 'Das sind viele Tage. Stark' },
  { id: 'de-031', lang: 'de', text: 'Absurd unterschätzt' },
  { id: 'de-032', lang: 'de', text: 'Gib dem Mann eine Medaille' },
  { id: 'de-033', lang: 'de', text: 'Lächerlich solide' },
  { id: 'de-034', lang: 'de', text: 'Unerschütterlich' },
  { id: 'de-035', lang: 'de', text: 'Für Leute wie dich wurden Kalender erfunden' },
  { id: 'de-036', lang: 'de', text: 'Zehn von zehn' },
  { id: 'de-037', lang: 'de', text: 'Deswegen bist du der Liebling' },
  { id: 'de-038', lang: 'de', text: 'Du machst Zahlen' },
  { id: 'de-039', lang: 'de', text: 'Offiziell im Tunnel' },
  { id: 'de-040', lang: 'de', text: 'Anscheinend keine freien Tage' },
  { id: 'de-041', lang: 'de', text: 'Die Konstanz ist echt einschüchternd' },
  { id: 'de-042', lang: 'de', text: 'Objektiv hervorragend' },
  { id: 'de-043', lang: 'de', text: 'Das ist Handwerkskunst' },
  { id: 'de-044', lang: 'de', text: 'Feine Arbeit' },
  { id: 'de-047', lang: 'de', text: 'Schau dir diesen Profi an' },
  { id: 'de-048', lang: 'de', text: 'Da macht jemand keine Witze' },
  { id: 'de-049', lang: 'de', text: 'Einfach inspirierend' },
  { id: 'de-050', lang: 'de', text: 'Lässt es leicht aussehen, ist es nicht' },
  { id: 'de-051', lang: 'de', text: 'Leise dominant' },
  { id: 'de-052', lang: 'de', text: 'So sieht Auftauchen aus' },
  { id: 'de-053', lang: 'de', text: 'Lehrbuchmässig' },
  { id: 'de-054', lang: 'de', text: 'Unfair konstant' },
  { id: 'de-055', lang: 'de', text: 'Einfach so gebaut' },
  { id: 'de-056', lang: 'de', text: 'Null Ausreden erkannt' },
  { id: 'de-057', lang: 'de', text: 'Die Latte hängt jetzt an der Decke' },
  { id: 'de-059', lang: 'de', text: 'Offizieller Tagessieger' },
  { id: 'de-060', lang: 'de', text: 'Was für Szenen' },
  { id: 'de-061', lang: 'de', text: 'Du hast das Ding gemacht. Schon wieder' },
  { id: 'de-062', lang: 'de', text: 'Zinseszins des Auftauchens' },
  { id: 'de-063', lang: 'de', text: 'Respekt, ganz ehrlich' },
  { id: 'de-064', lang: 'de', text: 'Das ist eine Meisterklasse' },
  { id: 'de-065', lang: 'de', text: 'Beiläufig exzellent' },
  { id: 'de-066', lang: 'de', text: 'Das ist der gute Stoff' },
  { id: 'de-067', lang: 'de', text: 'Jemand soll diese Energie abfüllen' },
  { id: 'de-068', lang: 'de', text: 'Volle Punktzahl' },
  { id: 'de-069', lang: 'de', text: 'Kein einziger verschwendeter Tag' },
  { id: 'de-070', lang: 'de', text: 'Das Durchziehen ist unwirklich' },
  { id: 'de-071', lang: 'de', text: 'Leise gewinnen' },
  { id: 'de-072', lang: 'de', text: 'Nie in Gefahr' },
  { id: 'de-073', lang: 'de', text: 'Das war nie knapp' },
  { id: 'de-074', lang: 'de', text: 'Eiskalt durchgezogen' },
  { id: 'de-075', lang: 'de', text: 'Sensationell' },
  { id: 'de-076', lang: 'de', text: 'Den Tag aufgemacht und gewonnen' },
  { id: 'de-077', lang: 'de', text: 'Tief beeindruckend' },
  { id: 'de-078', lang: 'de', text: 'Das ist deine Ursprungsgeschichte' },
  { id: 'de-080', lang: 'de', text: 'Entfesselte Disziplin' },
  { id: 'de-081', lang: 'de', text: 'Stoppt jemand mal den Zähler' },
  { id: 'de-082', lang: 'de', text: 'Die Belege stapeln sich' },
  { id: 'de-083', lang: 'de', text: 'Du machst, worüber andere reden' },
  { id: 'de-084', lang: 'de', text: 'Applaus. Echter Applaus' },
  { id: 'de-085', lang: 'de', text: 'Die Arbeit funktioniert' },
  { id: 'de-086', lang: 'de', text: 'Konstant lächerlich' },
  { id: 'de-087', lang: 'de', text: 'Keine Gedanken, nur Umsetzung' },
  { id: 'de-088', lang: 'de', text: 'Gebaut für die Ewigkeit' },
  { id: 'de-089', lang: 'de', text: 'Tag {days}. Absolutes Kino' },
  { id: 'de-090', lang: 'de', text: 'Das ist eine ernsthafte Serie' },
  { id: 'de-091', lang: 'de', text: 'Mühelos unerbittlich' },
  { id: 'de-092', lang: 'de', text: 'Das ist die Blaupause' },
  { id: 'de-093', lang: 'de', text: 'Schöne Arbeit' },
  { id: 'de-094', lang: 'de', text: 'Offizieller Grinder' },
  { id: 'de-095', lang: 'de', text: 'Machst, was du gesagt hast. Selten' },
  { id: 'de-096', lang: 'de', text: 'Extrem fokussiert' },
  { id: 'de-097', lang: 'de', text: 'Das ist Elite' },
  { id: 'de-098', lang: 'de', text: 'Ganz beiläufig am Durchdrehen (positiv)' },
  { id: 'de-099', lang: 'de', text: 'Wirklich inspirierend, ohne Ironie' },
  { id: 'de-100', lang: 'de', text: 'Schau dir dieses Durchziehen an' },
  { id: 'de-101', lang: 'de', text: 'Jemand soll ein Kamerateam schicken' },
  { id: 'de-102', lang: 'de', text: 'Unbeweglich' },
  { id: 'de-103', lang: 'de', text: 'Ehrlich einer der Grössten' },
  { id: 'de-104', lang: 'de', text: 'Keine Aussetzer' },
  { id: 'de-105', lang: 'de', text: 'Absolut eingestellt' },
  { id: 'de-106', lang: 'de', text: 'Das ist hörbare Disziplin' },
  { id: 'de-108', lang: 'de', text: 'Schon wieder den Standard gesetzt' },
  { id: 'de-109', lang: 'de', text: 'Man sieht deinen Schwung' },
  { id: 'de-110', lang: 'de', text: 'Nichts als Respekt' },
  { id: 'de-111', lang: 'de', text: 'Lächerlich, im besten Sinne' },
  { id: 'de-112', lang: 'de', text: 'Das ist Spitze' },
  { id: 'de-113', lang: 'de', text: 'Ruhig wie sonst was' },
  { id: 'de-114', lang: 'de', text: 'Offiziell harter Arbeiter' },
  { id: 'de-115', lang: 'de', text: 'Die Konstanz-Steuer ist bezahlt' },
  { id: 'de-116', lang: 'de', text: 'Du lässt das nach Routine aussehen' },
  { id: 'de-117', lang: 'de', text: 'Die Routine ist der Flex' },
  { id: 'de-118', lang: 'de', text: 'Nie verpasst, wird auch nicht passieren' },
  { id: 'de-119', lang: 'de', text: 'Unbeeindruckt, eingecremt, on Streak' },
  { id: 'de-120', lang: 'de', text: 'Das Mindset ist unwirklich' },
  { id: 'de-121', lang: 'de', text: 'Das Langweilige brillant machen' },
  { id: 'de-122', lang: 'de', text: 'Das ist ein ernsthafter Mensch' },
  { id: 'de-123', lang: 'de', text: 'Das sollte nicht möglich sein' },
  { id: 'de-124', lang: 'de', text: 'Eiskalt' },
  { id: 'de-125', lang: 'de', text: 'Voll. Da.' },
  { id: 'de-126', lang: 'de', text: 'Das kommt in die Highlights' },
  { id: 'de-127', lang: 'de', text: 'Da baut jemand was auf' },
  { id: 'de-128', lang: 'de', text: 'Leise Exzellenz' },
  { id: 'de-129', lang: 'de', text: 'Lehrbuch. Einrahmen' },
  { id: 'de-130', lang: 'de', text: 'Das ist ein Profi' },
  { id: 'de-131', lang: 'de', text: 'Grossen Respekt' },
  { id: 'de-132', lang: 'de', text: 'Unantastbar' },
  { id: 'de-133', lang: 'de', text: 'Absoluter Fels' },
  { id: 'de-134', lang: 'de', text: 'Deine Disziplin braucht eine eigene Postleitzahl' },
  { id: 'de-135', lang: 'de', text: 'Genau dafür gibt es diese App' },
  { id: 'de-136', lang: 'de', text: 'Unwirkliches Durchziehen' },
  { id: 'de-137', lang: 'de', text: 'Konstanz ist eine Superkraft und du hast sie' },
  { id: 'de-138', lang: 'de', text: 'Richtig gemacht' },
  { id: 'de-139', lang: 'de', text: 'Schau dir diesen Einsatz an' },
  { id: 'de-140', lang: 'de', text: 'Da hat jemand einen Plan und zieht ihn durch' },
  { id: 'de-141', lang: 'de', text: 'Das ist ein ernsthafter Typ' },
  { id: 'de-142', lang: 'de', text: 'Einfach exzellent' },
  { id: 'de-143', lang: 'de', text: 'Die Routine ist ungeschlagen' },
  { id: 'de-144', lang: 'de', text: 'Das war klinisch' },
  { id: 'de-145', lang: 'de', text: 'Keine verschwendete Bewegung' },
  { id: 'de-146', lang: 'de', text: 'Das ist meisterhaft' },
  { id: 'de-147', lang: 'de', text: 'Absolut nichts anzumerken' },
  { id: 'de-148', lang: 'de', text: 'Du bist der Massstab' },
  { id: 'de-149', lang: 'de', text: 'Unantastbare Form' },
  { id: 'de-150', lang: 'de', text: 'Ehrlich brillant' },
  { id: 'de-151', lang: 'de', text: 'So macht man das' },
  { id: 'de-152', lang: 'de', text: 'Extrem gut gespielt' },
  { id: 'de-153', lang: 'de', text: 'Schau dich an' },
  { id: 'de-154', lang: 'de', text: 'Die Serie ist jetzt ein Lebensstil' },
  { id: 'de-155', lang: 'de', text: 'Einsatz erkannt' },
  { id: 'de-156', lang: 'de', text: 'Offiziell unerbittlich' },
  { id: 'de-157', lang: 'de', text: 'Keine halben Sachen' },
  { id: 'de-158', lang: 'de', text: 'Meint es ernst' },
  { id: 'de-159', lang: 'de', text: 'Makellose Vibes' },
  { id: 'de-160', lang: 'de', text: 'Nichts Beiläufiges daran' },
  { id: 'de-161', lang: 'de', text: 'Reines Maschinenverhalten' },
  { id: 'de-162', lang: 'de', text: 'Die Konstanz ist laut' },
  { id: 'de-163', lang: 'de', text: 'Die Arbeit leise machen' },
  { id: 'de-164', lang: 'de', text: 'Totale Kontrolle' },
  { id: 'de-165', lang: 'de', text: 'Das ist jetzt Gewohnheit, keine Hoffnung' },
  { id: 'de-166', lang: 'de', text: 'Gnadenlos konstant' },
  { id: 'de-167', lang: 'de', text: 'Die Latte wurde wieder höher gelegt' },
  { id: 'de-168', lang: 'de', text: 'So sieht Verbindlichkeit aus' },
  { id: 'de-169', lang: 'de', text: 'Da ist jemand aufgewacht und hat geliefert' },
  { id: 'de-170', lang: 'de', text: 'Das ist ein ernsthaftes Ergebnis' },
  { id: 'de-171', lang: 'de', text: 'Keine Lücken' },
  { id: 'de-172', lang: 'de', text: 'Das Durchziehen ist Elite' },
  { id: 'de-173', lang: 'de', text: 'Beeindruckend trifft es nicht' },
  { id: 'de-174', lang: 'de', text: 'Extrem solide' },
  { id: 'de-175', lang: 'de', text: 'Echte machen das' },
  { id: 'de-176', lang: 'de', text: 'Konstant herausragend' },
  { id: 'de-177', lang: 'de', text: 'Das ist ein richtiger Einsatz' },
  { id: 'de-178', lang: 'de', text: 'Schau dir die Form dieser Serie an' },
  { id: 'de-179', lang: 'de', text: 'Macht es wirklich' },
  { id: 'de-180', lang: 'de', text: 'Perfekt umgesetzt' },
  { id: 'de-181', lang: 'de', text: 'Absolut fokussiert' },
  { id: 'de-182', lang: 'de', text: 'Nichts zu verbessern' },
  { id: 'de-183', lang: 'de', text: 'Reine Qualität' },
  { id: 'de-184', lang: 'de', text: 'Lehrbuch-Konstanz' },
  { id: 'de-185', lang: 'de', text: 'Das ist eine ernsthafte Gewohnheit' },
  { id: 'de-186', lang: 'de', text: 'Ehrlich exzellente Arbeit' },
  { id: 'de-187', lang: 'de', text: 'Unerreicht' },
  { id: 'de-188', lang: 'de', text: 'Da ist jemand auf Mission' },
  { id: 'de-189', lang: 'de', text: 'Das ist Hingabe' },
  { id: 'de-190', lang: 'de', text: 'Komplette Kontrolle' },
  { id: 'de-191', lang: 'de', text: 'Exzellent wie immer' },
  { id: 'de-192', lang: 'de', text: 'Gar nichts anzumerken' },
  { id: 'de-193', lang: 'de', text: 'Das ist Elite-Verhalten' },
  { id: 'de-194', lang: 'de', text: 'Volle Verbindlichkeit' },
  { id: 'de-195', lang: 'de', text: 'Schau dir diese Disziplin an' },
  { id: 'de-196', lang: 'de', text: 'Konstant brillant' },
  { id: 'de-197', lang: 'de', text: 'Eine ernsthafte Leistung' },
  { id: 'de-198', lang: 'de', text: 'Das ist aussergewöhnlich' },
  { id: 'de-199', lang: 'de', text: 'Unglaublich konstant' },
  { id: 'de-200', lang: 'de', text: 'Da ist jemand anders' },
  { id: 'de-201', lang: 'de', text: 'Absolut hervorragend' },
  { id: 'de-202', lang: 'de', text: 'Das ist Qualität' },
  { id: 'de-203', lang: 'de', text: 'Wirklich sehr beeindruckend' },
  { id: 'de-204', lang: 'de', text: 'Echte Konstanz' },
  { id: 'de-205', lang: 'de', text: 'Nichts als Exzellenz' },
  { id: 'de-206', lang: 'de', text: 'Das ist richtige Arbeit' },
  { id: 'de-207', lang: 'de', text: 'Voll dabei' },
  { id: 'de-208', lang: 'de', text: 'Herausragend' },
  { id: 'de-209', lang: 'de', text: 'Richtig gut' },
  { id: 'de-210', lang: 'de', text: 'Schau dir das an' },
  { id: 'de-211', lang: 'de', text: 'Bemerkenswert' },
  { id: 'de-212', lang: 'de', text: 'Einfach brillant' },
  { id: 'de-213', lang: 'de', text: 'Sehr gut gemacht' },
  { id: 'de-214', lang: 'de', text: 'Extrem beeindruckend' },
  { id: 'de-215', lang: 'de', text: 'Ehrlich grossartig' },
  { id: 'gsw-001', lang: 'gsw', text: 'Du bisch en Chrampfer' },
  { id: 'gsw-002', lang: 'gsw', text: 'Läuft bi dir' },
  { id: 'gsw-003', lang: 'gsw', text: 'Sackstark' },
  { id: 'gsw-006', lang: 'gsw', text: 'Du bisch e Rakete' },
  { id: 'gsw-007', lang: 'gsw', text: 'Chum, gib Gas' },
  { id: 'gsw-008', lang: 'gsw', text: 'Hesch guet gmacht' },
  { id: 'gsw-009', lang: 'gsw', text: 'Du bisch nöd normal' },
  { id: 'gsw-011', lang: 'gsw', text: 'Respäkt, ehrlich' },
  { id: 'gsw-012', lang: 'gsw', text: 'Du bisch e Maschine' },
  { id: 'gsw-013', lang: 'gsw', text: 'Eifach nur stark' },
  { id: 'gsw-014', lang: 'gsw', text: 'Das isch mega' },
  { id: 'gsw-015', lang: 'gsw', text: 'Voll de Hammer' },
  { id: 'gsw-016', lang: 'gsw', text: 'Du rockst das' },
  { id: 'gsw-018', lang: 'gsw', text: 'Du bisch e Wucht' },
  { id: 'gsw-019', lang: 'gsw', text: 'Eifach abliefere' },
  { id: 'gsw-020', lang: 'gsw', text: 'Das isch Chnorz, aber du machsch es' },
  { id: 'gsw-021', lang: 'gsw', text: 'Bisch am Chrampfe, gell' },
  { id: 'gsw-022', lang: 'gsw', text: 'Du häsch en Lauf' },
  { id: 'gsw-023', lang: 'gsw', text: 'Ganz starchi Sach' },
  { id: 'gsw-025', lang: 'gsw', text: 'Eifach dure zieh' },
  { id: 'gsw-027', lang: 'gsw', text: 'Du bisch e Bank' },
  { id: 'gsw-028', lang: 'gsw', text: 'Ganz ehrlich: Respäkt' },
  { id: 'gsw-029', lang: 'gsw', text: 'Du machsch das eifach' },
  { id: 'gsw-030', lang: 'gsw', text: 'Chum, du packsch das' },
  { id: 'gsw-031', lang: 'gsw', text: 'Du bisch am Liefere' },
  { id: 'gsw-032', lang: 'gsw', text: 'Das isch Klasse' },
  { id: 'gsw-033', lang: 'gsw', text: 'Du bisch guet drin' },
  { id: 'gsw-034', lang: 'gsw', text: 'Eifach wiiter so' },
  { id: 'gsw-036', lang: 'gsw', text: 'Das isch schoen zum aaluege' },
  { id: 'gsw-037', lang: 'gsw', text: 'Du häsch das im Griff' },
  { id: 'gsw-038', lang: 'gsw', text: 'Ganz starchi Leistig' },
  { id: 'gsw-039', lang: 'gsw', text: 'Du bisch am Rocke' },
  { id: 'gsw-040', lang: 'gsw', text: 'Das isch Spitze' },
  { id: 'gsw-041', lang: 'gsw', text: 'Du machsch Sache' },
  { id: 'gsw-042', lang: 'gsw', text: 'Eifach nur Respäkt' },
  { id: 'gsw-043', lang: 'gsw', text: 'Du bisch dra' },
  { id: 'gsw-044', lang: 'gsw', text: 'Das laufft' },
  { id: 'gsw-045', lang: 'gsw', text: 'Du bisch konstant wie nöd gschiid' },
  { id: 'gsw-046', lang: 'gsw', text: 'Eifach ächt stark' },
  { id: 'gsw-047', lang: 'gsw', text: 'Du bisch e Legend' },
  { id: 'gsw-049', lang: 'gsw', text: 'Du bisch nöd z stoppe' },
  { id: 'gsw-050', lang: 'gsw', text: 'Chum, no meh' },
  { id: 'gsw-051', lang: 'gsw', text: 'Du häsch Biss' },
  { id: 'gsw-052', lang: 'gsw', text: 'Ganz grossi Klass' },
  { id: 'gsw-053', lang: 'gsw', text: 'Du bisch am Zug' },
  { id: 'gsw-054', lang: 'gsw', text: 'Das isch souber' },
  { id: 'gsw-055', lang: 'gsw', text: 'Du machsch das richtig' },
  { id: 'gsw-056', lang: 'gsw', text: 'Eifach guet' },
  { id: 'gsw-057', lang: 'gsw', text: 'Du bisch en Fels' },
  { id: 'gsw-058', lang: 'gsw', text: 'Das isch stabil' },
  { id: 'gsw-059', lang: 'gsw', text: 'Du bisch am Dranblibe' },
  { id: 'gsw-060', lang: 'gsw', text: 'Ganz starch, ehrlich' },
  { id: 'gsw-061', lang: 'gsw', text: 'Du bisch e Granate' },
  { id: 'gsw-062', lang: 'gsw', text: 'Das isch top' },
  { id: 'gsw-063', lang: 'gsw', text: 'Du häsch Dampf' },
  { id: 'gsw-064', lang: 'gsw', text: 'Eifach nur guet' },
  { id: 'gsw-065', lang: 'gsw', text: 'Du bisch en Kämpfer' },
  { id: 'gsw-066', lang: 'gsw', text: 'Das isch beeindruckend' },
  { id: 'gsw-067', lang: 'gsw', text: 'Du bisch am Marschiere' },
  { id: 'gsw-068', lang: 'gsw', text: 'Ganz saubere Sach' },
  { id: 'gsw-069', lang: 'gsw', text: 'Du bisch en Held' },
  { id: 'gsw-070', lang: 'gsw', text: 'Das isch richtig guet' },
  { id: 'gsw-071', lang: 'gsw', text: 'Du machsch kei Witz' },
  { id: 'gsw-072', lang: 'gsw', text: 'Eifach durezieh' },
  { id: 'gsw-073', lang: 'gsw', text: 'Du bisch am Ball' },
  { id: 'gsw-074', lang: 'gsw', text: 'Das isch stark, ehrlich' },
  { id: 'gsw-075', lang: 'gsw', text: 'Du bisch en Profi' },
  { id: 'gsw-076', lang: 'gsw', text: 'Ganz starchi Nummere' },
  { id: 'gsw-077', lang: 'gsw', text: 'Du bisch am Gas gäh' },
  { id: 'gsw-078', lang: 'gsw', text: 'Das isch Weltklass' },
  { id: 'gsw-079', lang: 'gsw', text: 'Du häsch das druff' },
  { id: 'gsw-080', lang: 'gsw', text: 'Eifach nur wow' },
  { id: 'gsw-081', lang: 'gsw', text: 'Du bisch am Abliefere' },
  { id: 'gsw-083', lang: 'gsw', text: 'Du bisch dra blibe' },
  { id: 'gsw-084', lang: 'gsw', text: 'Ganz ehrlich stark' },
  { id: 'gsw-085', lang: 'gsw', text: 'Du bisch en Chrampfer, aber gern' },
  { id: 'gsw-086', lang: 'gsw', text: 'Das isch Hammer' },
  { id: 'gsw-087', lang: 'gsw', text: 'Du machsch das super' },
  { id: 'gsw-088', lang: 'gsw', text: 'Eifach mega' },
  { id: 'gsw-089', lang: 'gsw', text: 'Du bisch am Durezieh' },
  { id: 'gsw-090', lang: 'gsw', text: 'Das isch riesig' },
  { id: 'gsw-091', lang: 'gsw', text: 'Du häsch Charakter' },
  { id: 'gsw-092', lang: 'gsw', text: 'Ganz starch gmacht' },
  { id: 'gsw-093', lang: 'gsw', text: 'Du bisch e Bank, ehrlich' },
  { id: 'gsw-094', lang: 'gsw', text: 'Das isch grossartig' },
  { id: 'gsw-095', lang: 'gsw', text: 'Du bisch am Rolle' },
  { id: 'gsw-096', lang: 'gsw', text: 'Eifach klasse' },
  { id: 'gsw-097', lang: 'gsw', text: 'Du bisch nöd uufzhalte' },
  { id: 'gsw-098', lang: 'gsw', text: 'Das isch bäumig' },
  { id: 'gsw-099', lang: 'gsw', text: 'Du machsch das mit Stil' },
  { id: 'gsw-100', lang: 'gsw', text: 'Ganz starchi Wuche' },
  { id: 'gsw-101', lang: 'gsw', text: 'Du bisch de Beste' },
  { id: 'gsw-102', lang: 'gsw', text: 'Du bisch e Wucht, ehrlich' },
  { id: 'gsw-103', lang: 'gsw', text: 'Das häsch du toll gmacht' },
  { id: 'gsw-104', lang: 'gsw', text: 'Chapeau' },
  { id: 'gsw-105', lang: 'gsw', text: 'Du bisch en Vorbild' },
  { id: 'gsw-106', lang: 'gsw', text: 'Ganz schön stark, du' },
  { id: 'gsw-107', lang: 'gsw', text: 'Du zieh das würkli dure' },
  { id: 'gsw-108', lang: 'gsw', text: 'Das isch grosse Klass' },
  { id: 'gsw-109', lang: 'gsw', text: 'Du bisch verlässlich wie sonst nüt' },
  { id: 'gsw-110', lang: 'gsw', text: 'Schön zum gseh, wie du dranbliibsch' },
  { id: 'gsw-111', lang: 'gsw', text: 'Du machsch das mit Herz' },
  { id: 'gsw-112', lang: 'gsw', text: 'Eifach en starche Typ' },
  { id: 'gsw-113', lang: 'gsw', text: 'Du bisch am richtige Wäg' },
  { id: 'gsw-114', lang: 'gsw', text: 'Das isch würkli beeindruckend' },
  { id: 'gsw-115', lang: 'gsw', text: 'Du gisch nie uf' },
  { id: 'gsw-116', lang: 'gsw', text: 'Mega, wie du das durezieh' },
  { id: 'gsw-117', lang: 'gsw', text: 'Du häsch das verdient' },
  { id: 'gsw-118', lang: 'gsw', text: 'Ganz ehrlich: chapeau' },
  { id: 'gsw-119', lang: 'gsw', text: 'Du bisch en Fels i de Brandig' },
];

const BY_ID = new Map(HYPE_PHRASES.map((p) => [p.id, p]));

export function getHypePhrase(id: string): HypePhrase | undefined {
  return BY_ID.get(id);
}

/** Every phrase a given locale is allowed to draw from. */
export function phrasesForLocale(locale: Locale): HypePhrase[] {
  const pools = POOLS_FOR_LOCALE[locale] ?? POOLS_FOR_LOCALE.en;
  return HYPE_PHRASES.filter((p) => pools.includes(p.lang));
}

/**
 * Draws a phrase for this locale, never repeating `excludeId` — so re-rolling
 * always visibly changes the sentence rather than sometimes landing on the
 * same one and looking broken.
 */
export function pickRandomHypePhrase(locale: Locale, excludeId?: string | null): HypePhrase {
  const pool = phrasesForLocale(locale);
  const candidates = excludeId ? pool.filter((p) => p.id !== excludeId) : pool;
  // Only possible with a pool of one, which no locale has — but never throw.
  const list = candidates.length > 0 ? candidates : pool;
  return list[Math.floor(Math.random() * list.length)];
}

/**
 * The phrase as displayed. `vars` fills placeholders such as {days}; a phrase
 * that uses one and is rendered without it would show the raw braces, which
 * src/test/hype-phrases.test.ts guards against.
 */
export function localizedHypePhrase(
  phrase: HypePhrase,
  vars?: Record<string, string | number>
): string {
  return interpolate(phrase.text, vars);
}
